version: '2'

services:
  mysqld_data:
    image: percona:latest
    container_name: mysqld_data
    entrypoint: /bin/true
    labels:
      - "mon.percona.container_type=data_container"

  mysqld:
    image: percona:latest
    container_name: db1_mysql
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d/
    volumes_from:
      - mysqld_data
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - dbnode
    labels:
      - "mon.percona.container_type=mysql"

  cadvisor:
    image: google/cadvisor:latest
    container_name: db1_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - dbnode
    labels:
      - "mon.percona.container_type=collector"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: db1_node_exporter
    ports:
      - "9100:9100"
    networks:
      - dbnode
    command: -collectors.enabled=diskstats,filesystem,loadavg,meminfo,netdev,stat,time,uname
    labels:
      - "mon.percona.container_type=collector"

  mysqld_exporter_high_res:
    image: prom/mysqld-exporter:latest
    container_name: db1_mysqld_exporter_hres
    environment:
      - DATA_SOURCE_NAME=prometheus:prometheus@(db1_mysql:3306)/
    ports:
      - "9104:9104"
    networks:
      - dbnode
    command: ["-web.listen-address=:9104", "-collect.global_status=true", "-collect.global_variables=false", "-collect.slave_status=false", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]
    labels:
      - "mon.percona.container_type=collector"
    depends_on:
      - mysqld

  mysqld_exporter_med_res:
    image: prom/mysqld-exporter:latest
    container_name: db1_mysqld_exporter_mres
    environment:
      - DATA_SOURCE_NAME=prometheus:prometheus@(db1_mysql:3306)/
    ports:
      - "9105:9105"
    networks:
      - dbnode
    command: ["-web.listen-address=:9105", "-collect.global_status=false", "-collect.global_variables=false", "-collect.slave_status=true", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=true", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=true", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=true"]
    labels:
      - "mon.percona.container_type=collector"
    depends_on:
      - mysqld

  mysqld_exporter_low_res:
    image: prom/mysqld-exporter:latest
    container_name: db1_mysqld_exporter_lres
    environment:
      - DATA_SOURCE_NAME=prometheus:prometheus@(db1_mysql:3306)/
    ports:
      - "9106:9106"
    networks:
      - dbnode
    command: ["-web.listen-address=:9106", "-collect.global_status=false", "-collect.global_variables=true", "-collect.slave_status=false", "-collect.info_schema.tables=true", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=true", "-collect.info_schema.tables=true", "-collect.auto_increment.columns=true", "-collect.info_schema.tablestats=true", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=true", "-collect.perf_schema.indexiowaits=true", "-collect.perf_schema.tableiowaits=true", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]
    labels:
      - "mon.percona.container_type=collector"
    depends_on:
      - mysqld

  sysbench:
    build:
      context: ./sysbench
    container_name: db1_sysbench
    volumes:
      - ./sysbench/scripts/run:/scripts
    networks:
      - dbnode 
    labels:
      - "mon.percona.container_type=load_test"
    depends_on:
      - mysqld

networks:
  dbnode:
    external: 
      name: monitor_dbnode
