version: '2'

services:
  prometheus_data:
    image: prom/prometheus
    container_name: prometheus_data
    entrypoint: /bin/true

  grafana_data:
    image: grafana/grafana
    container_name: grafana_data
    volumes: 
      - /usr/share/grafana
    entrypoint: /bin/true

  influx_data:
    image: tutum/influxdb
    container_name: influx_data
    command: /bin/true

  influxdb:
    image: tutum/influxdb
    container_name: percona_influxdb
    volumes_from: 
      - influx_data
    environment:
      - PRE_CREATE_DB=prometheus
    ports:
      - "8083:8083"
      - "8086:8086"
    networks:
      - percona_monitor

  prometheus:
    image: prom/prometheus
    container_name: percona_prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
    volumes_from:
      - prometheus_data
    ports:
      - "9090:9090"
    networks:
      - percona_monitor
      - example_dbnode
    command: [ "-config.file=/etc/prometheus/prometheus.yml", 
               "-storage.local.path=/prometheus", 
               "-storage.local.retention=168h", 
               "-storage.local.memory-chunks=524288", 
               "-storage.remote.influxdb-url=http://percona_influxdb:8086", 
               "-web.console.libraries=/etc/prometheus/console_libraries", 
               "-web.console.templates=/etc/prometheus/consoles" ]
    depends_on:
      - influxdb

  grafana_pre:
    build:
      context: ./grafana/scripts
    container_name: percona_grafana_pre
    volumes:
      - ./grafana/scripts/pre-scripts:/scripts
    volumes_from:
      - grafana_data
    networks:
      - percona_monitor
    command: /scripts/run.sh

  grafana:
    image: grafana/grafana
    container_name: percona_grafana
    volumes: 
      - ./grafana/scripts/run/scripts:/scripts
      - ./grafana/config:/etc/grafana
    volumes_from:
      - grafana_data
    ports:
      - "3000:3000"
    networks:
      - percona_monitor
    entrypoint: /scripts/run.sh
    depends_on:
      - prometheus
      - influxdb
      - grafana_pre

  grafana_post:
    build:
      context: ./grafana/scripts
    container_name: percona_grafana_post
    volumes:
      - ./grafana/scripts/post-scripts:/scripts
    volumes_from: 
      - grafana_data
    environment:
      - GRAFANA_HOST=percona_grafana
    networks:
      - percona_monitor
    command: /scripts/run.sh
    depends_on:
      - grafana

  influxdb_post:
    build:
      context: ./influxdb/scripts
    container_name: percona_influxdb_post
    volumes:
      - ./influxdb/scripts/post-scripts:/scripts
    environment:
      - INFLUXDB_HOST=percona_influxdb
    networks:
      - percona_monitor
    command: /scripts/run.sh
    depends_on:
      - influxdb

networks:
  percona_monitor:
    driver: bridge
  example_dbnode:
    driver: bridge
