global:
  scrape_interval:     5s
  evaluation_interval: 5s
 
scrape_configs:
  - job_name: monitor
    target_groups:
      - targets: ['node_exporter_1:9100', 'mysqld_exporter_1:9104']
        labels:
          alias: db1
