global:
  scrape_interval:     5s
  evaluation_interval: 5s
 
scrape_configs:
  - job_name: monitor
    target_groups:
      - targets: ['db1_node_exporter:9100', 'db1_mysqld_exporter:9104', 'db1_cadvisor:8080']
        labels:
          alias: db1
