global:
  scrape_interval:     1s
  scrape_timeout:      1s
  evaluation_interval: 5s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: linux
    static_configs:
      - targets: ['db1_node_exporter:9100']
        labels:
          alias: db1

  - job_name: docker
    static_configs:
      - targets: ['db1_cadvisor:8080']
        labels:
          alias: db1

  - job_name: mysql-hres
    static_configs:
      - targets: ['db1_mysqld_exporter_hres:9104']
        labels:
          alias: db1

  - job_name: mysql-mres
    scrape_interval: 5s
    scrape_timeout: 1s
    static_configs:
      - targets: ['db1_mysqld_exporter_mres:9105']
        labels:
          alias: db1

  - job_name: mysql-lres
    scrape_interval: 60s
    scrape_timeout: 5s
    static_configs:
      - targets: ['db1_mysqld_exporter_lres:9106']
        labels:
          alias: db1
